name: Stop VPS

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'GitHub Run ID to cancel'
        required: true

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          run_id: ${{ github.event.inputs.run_id }}
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Done
        run: echo "✅ VPS Run ${{ github.event.inputs.run_id }} stopped."
